### ISSUE TITLE
Is there an independent and repetitive simulation for each pair of ligands?

### ISSUE THREAD

**Issue by 9527567** [EricChen521/ATM_MerckSet#5]
Have you evaluated stability?

**Comment by EricChen521** [comment]
For this paper, we only did one calculation for each pair due to the large number of pairs in total. We have used ATM for a while now and the algorithm is quite stable.  When the ATM simulation crashes,  it is mostly because of inappropriate system preparation or the mismatched ligand atom index in the ATM control file.

**Comment by 9527567** [comment]
Thank you.
